language: node_js
node_js:
- '4'
- '6'
sudo: false
env:
  TOKEN:
    secure: TWUi53rBusnowvSZEXz4jYoMDbSrmeQexF3atCzl5gK/s/0rvaAhiw6nbEa7dy8KdIUcOFApQ8cBozV4q90aEdTZvniEfNRnil/2FeQ0dW45PlnpJhanMm51g3K/PdErnmCHyr/u8XrsOhP404EwbI2EWfGQ0URPZi4yCoSLjFxX3vrXTAABFm3jGS2KW3o1NZELZV9QNCLKH7hzGLcsOa0qG+FPA2VudrrYnM/efB+/qo5Nd7fOJbML0qNPhKHxFeW4ruYC5hqzIEClNb9ttU8AGcErSvRzYkdtgTA/ehc3lcxtibcULb6/AcG9QCu9/yUr3dEMLgr2p79Z9LmF9HWcOdRZgqrkLZ93EvKnMIFiJcI7Qitz+t/EZkaAQLHz96i4U2dAcIGMi9pW8SI9WD7RmuL5pHKCtyBji4v9cB5V6eHrWM3VUmpvLnyXuVIoO/y+Uhz+TzOLy8iTojQHxomPaTBQaeRvUfXZS5rbndqNExwE7dKcYo+zyXbEM45AOLgCW8HL7RCYZbuyDlGDywD0z8K3R1OhyWbKzDPIR3Z71m51v5Jxsm3ZIDUuR8DwMmnUktA0gs3x0ZFpxcUp5q4+qj19ZiviSJS5DYGfmNN9n861xXHRFks6DlgH2Ebnk0aOld30xUcnPw44YFlJNpMRV/W1K0pOQO5eD/Dt9N4=
